// <auto-generated />
using System;
using Bolt.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bolt.Persistence.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251214200507_createdatabaseagain")]
    partial class createdatabaseagain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bolt.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RideId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("PassengerId");

                    b.HasIndex("RideId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Bolt.Domain.Entities.RideOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("PassengerId");

                    b.HasIndex("Status");

                    b.ToTable("RideOrders");
                });

            modelBuilder.Entity("Bolt.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("UserRole").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Bolt.Domain.Entities.Driver", b =>
                {
                    b.HasBaseType("Bolt.Domain.Entities.User");

                    b.Property<string>("CompletedRideIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompletedRideIds");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehiclePlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasDiscriminator().HasValue("Driver");
                });

            modelBuilder.Entity("Bolt.Domain.Entities.Passenger", b =>
                {
                    b.HasBaseType("Bolt.Domain.Entities.User");

                    b.Property<string>("PreferredPaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RideHistoryIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RideHistoryIds");

                    b.HasDiscriminator().HasValue("Passenger");
                });

            modelBuilder.Entity("Bolt.Domain.Entities.Review", b =>
                {
                    b.OwnsOne("Bolt.Domain.ValueObjects.Rating", "Rating", b1 =>
                        {
                            b1.Property<Guid>("ReviewId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("TotalReviews")
                                .HasColumnType("int");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(3,1)");

                            b1.HasKey("ReviewId");

                            b1.ToTable("Reviews");

                            b1.WithOwner()
                                .HasForeignKey("ReviewId");
                        });

                    b.Navigation("Rating")
                        .IsRequired();
                });

            modelBuilder.Entity("Bolt.Domain.Entities.RideOrder", b =>
                {
                    b.OwnsOne("Bolt.Domain.ValueObjects.Address", "DestinationAddress", b1 =>
                        {
                            b1.Property<Guid>("RideOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("RideOrderId");

                            b1.ToTable("RideOrders");

                            b1.WithOwner()
                                .HasForeignKey("RideOrderId");

                            b1.OwnsOne("Bolt.Domain.ValueObjects.Location", "Location", b2 =>
                                {
                                    b2.Property<Guid>("AddressRideOrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Latitude")
                                        .HasColumnType("decimal(9,6)");

                                    b2.Property<decimal>("Longitude")
                                        .HasColumnType("decimal(9,6)");

                                    b2.HasKey("AddressRideOrderId");

                                    b2.ToTable("RideOrders");

                                    b2.WithOwner()
                                        .HasForeignKey("AddressRideOrderId");
                                });

                            b1.Navigation("Location")
                                .IsRequired();
                        });

                    b.OwnsOne("Bolt.Domain.ValueObjects.Money", "EstimatedFare", b1 =>
                        {
                            b1.Property<Guid>("RideOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("RideOrderId");

                            b1.ToTable("RideOrders");

                            b1.WithOwner()
                                .HasForeignKey("RideOrderId");
                        });

                    b.OwnsOne("Bolt.Domain.ValueObjects.Money", "FinalFare", b1 =>
                        {
                            b1.Property<Guid>("RideOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("RideOrderId");

                            b1.ToTable("RideOrders");

                            b1.WithOwner()
                                .HasForeignKey("RideOrderId");
                        });

                    b.OwnsOne("Bolt.Domain.ValueObjects.Address", "PickupAddress", b1 =>
                        {
                            b1.Property<Guid>("RideOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("RideOrderId");

                            b1.ToTable("RideOrders");

                            b1.WithOwner()
                                .HasForeignKey("RideOrderId");

                            b1.OwnsOne("Bolt.Domain.ValueObjects.Location", "Location", b2 =>
                                {
                                    b2.Property<Guid>("AddressRideOrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Latitude")
                                        .HasColumnType("decimal(9,6)");

                                    b2.Property<decimal>("Longitude")
                                        .HasColumnType("decimal(9,6)");

                                    b2.HasKey("AddressRideOrderId");

                                    b2.ToTable("RideOrders");

                                    b2.WithOwner()
                                        .HasForeignKey("AddressRideOrderId");
                                });

                            b1.Navigation("Location")
                                .IsRequired();
                        });

                    b.Navigation("DestinationAddress")
                        .IsRequired();

                    b.Navigation("EstimatedFare")
                        .IsRequired();

                    b.Navigation("FinalFare");

                    b.Navigation("PickupAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("Bolt.Domain.Entities.Driver", b =>
                {
                    b.OwnsOne("Bolt.Domain.ValueObjects.Rating", "Rating", b1 =>
                        {
                            b1.Property<Guid>("DriverId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("DriverId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("DriverId");
                        });

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("Bolt.Domain.Entities.Passenger", b =>
                {
                    b.OwnsOne("Bolt.Domain.ValueObjects.Rating", "Rating", b1 =>
                        {
                            b1.Property<Guid>("PassengerId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("PassengerId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("PassengerId");
                        });

                    b.Navigation("Rating");
                });
#pragma warning restore 612, 618
        }
    }
}
